list_of_airlines=["AI","SJ","JA","EM","AA"]
new_list=list_of_airlines[-5:]
print(new_list)
new_list=list_of_airlines[1:-2]
print(new_list)
new_list=list_of_airlines[:5]
print(new_list)
new_list=list_of_airlines[-6:]
print(new_list)
